
import { InterviewResult } from '../types';

export const exportReportToText = (results: InterviewResult[], jobTitle: string) => {
  if (!results.length) return;

  const totalScore = results.reduce((acc, result) => acc + result.feedback.score, 0);
  const averageScore = Math.round((totalScore / (results.length * 10)) * 100);
  const dateStr = new Date().toLocaleDateString();

  let content = `AI INTERVIEW COACH - PERFORMANCE REPORT\n`;
  content += `========================================\n\n`;
  content += `Job Title: ${jobTitle}\n`;
  content += `Date: ${dateStr}\n`;
  content += `Overall Performance: ${averageScore}%\n\n`;
  content += `----------------------------------------\n\n`;

  results.forEach((result, index) => {
    content += `QUESTION ${index + 1}: ${result.question.question}\n`;
    content += `Persona: ${result.question.persona}\n`;
    content += `Your Answer: "${result.answer}"\n`;
    content += `Score: ${result.feedback.score}/10\n`;
    content += `Rating: ${result.feedback.rating}\n\n`;

    content += `Strengths:\n`;
    result.feedback.strengths.forEach(s => content += `- ${s}\n`);
    
    content += `\nAreas for Improvement:\n`;
    result.feedback.weaknesses.forEach(w => content += `- ${w}\n`);

    content += `\nMatched Keywords: ${result.feedback.matchedKeywords.join(', ') || 'None'}\n`;
    content += `Missed Keywords: ${result.feedback.missedKeywords.join(', ') || 'None'}\n`;
    
    content += `\nSuggested Ideal Answer:\n${result.feedback.idealAnswer}\n`;
    content += `\n----------------------------------------\n\n`;
  });

  content += `Generated by Coach.AI - Your personal mock interviewer.\n`;

  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `Interview_Report_${jobTitle.replace(/\s+/g, '_')}_${dateStr.replace(/\//g, '-')}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
